server:
  port: 8081
  servlet:    context-path: /
spring:  datasource:    url: jdbc:mysql://localhost:3306/covid19?useUnicode=true&serverTimezone=GMT&useSSL=false&characterEncoding=utf8
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
  redis:    database: 0
    host: 127.0.0.1
    port: 6379
    password: 
mybatis-plus:
#  mapper-locations: mapper/*.xml
  type-aliases-package: com.example.covid.entity
  check-config-location: true
  configuration:    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#jwt
jwt:
  token-header-key: Authorization
  token-prefix: covid
  token-expiration: 43200000 #12*60*60*1000 12小时
  token-secret: covid-web